In [2]:
import numpy as np
a = [1,2,3]
print("Data Of A is - ",a)

Data Of A is -  [1, 2, 3]


In [4]:
a = np.array([1,2,3])
print("Array is - ",a)

Array is -  [1 2 3]


In [7]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
addition = a+b
subtraction = a-b
multiplication = a*b
division = a/b
print("----------")
print("Addition is - \n",addition)
print("----------")
print("Divison is - \n",division)
print("----------")
print("Multiplication is - \n",multiplication)
print("----------")
print("Subtraction is - \n",subtraction)

----------
Addition is - 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
----------
Divison is - 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
----------
Multiplication is - 
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]]
----------
Subtraction is - 
 [[0 0 0]
 [0 0 0]
 [0 0 0]]


In [9]:
print(type(a))

<class 'numpy.ndarray'>


In [11]:
print("Size of array a is - ",a.size)

Size of array a is -  9


In [13]:
print("Dimenstion of array a is - ",a.ndim)

Dimenstion of array a is -  2


In [16]:
age = int(input("Enter Your Age : "))
print("Your Age is - ",age)

if age > 18:
  print("You are eligible for votting")
else:
  print("Sorry! You aren't eligible for votting")

Enter Your Age : 21
Your Age is -  21
You are eligible for votting
