In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([(1,2,3),(4,5,6)])

print("A :",a)
print("B :",b)

A : [1 2 3]
B : [[1 2 3]
 [4 5 6]]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([(1,2,3), (4,5,6)])

print("----------")
print("A :",a)
print("A's ndim",a.ndim)
print("A's size",a.size)
print("A's shape",a.shape)
print("A's dtype",a.dtype)
print("A's itemsize",a.itemsize)
print("----------")
print("B :",b)
print("B's ndim {}".format(b.ndim))
print("B's size",b.size)
print("B's shape",b.shape)
print("B's dtype",b.dtype)
print("B's itemsize",b.itemsize)

----------
A : [1 2 3]
A's ndim 1
A's size 3
A's shape (3,)
A's dtype int64
A's itemsize 8
----------
B : [[1 2 3]
 [4 5 6]]
B's ndim 2
B's size 6
B's shape (2, 3)
B's dtype int64
B's itemsize 8


In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print("B is :",b)

B is : [[1 2 3]
 [4 5 6]]


In [ ]:
c = np.array(1)
print("C is :",c)

C is : 1


In [ ]:
raj = np.array([[1,2],[3,4]],dtype=complex)
print(raj)

[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [ ]:
raj = np.zeros((2,3))
print("Zeros Array : {}".format(raj))
print("\n")
b = np.ones((2,3))
print("Ones Array :",b)
print("\n")
c = np.empty((2,3))
print("Empty Array :",c)
print("\n")
d = np.arange(1,2,0.2)
print("Arange Array :",d)
print("\n")
e = np.linspace(1,3,7)
print("Linespace Array :",e)
print("\n")
f = np.random.random((2,3))
print("Random Array :",f)

Zeros Array : [[0. 0. 0.]
 [0. 0. 0.]]


Ones Array : [[1. 1. 1.]
 [1. 1. 1.]]


Empty Array : [[1. 1. 1.]
 [1. 1. 1.]]


Arange Array : [1.  1.2 1.4 1.6 1.8]


Linespace Array : [1.         1.33333333 1.66666667 2.         2.33333333 2.66666667
 3.        ]


Random Array : [[0.86851345 0.21687216 0.57499669]
 [0.94852018 0.55659306 0.74554167]]


In [ ]:
seven = np.arange(7,71,7)
print("Table of 7 is : ",seven)

Table of 7 is :  [ 7 14 21 28 35 42 49 56 63 70]


In [ ]:
ab = np.zeros((1,3))
bc = np.ones((3,1))
print("AB Var is :",ab)
print("\n")
print("bc Var is :\n",bc)
print("\n")
rang = np.arange(11,20)
print("Range Array is :",rang)
rang1 = rang.reshape(3,3)
rang1

AB Var is : [[0. 0. 0.]]


bc Var is :
 [[1.]
 [1.]
 [1.]]


Range Array is : [11 12 13 14 15 16 17 18 19]


array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
new = np.array(["araj","b","c","d"])
new

ran = new.reshape(2,2)
ran

array([['araj', 'b'],
       ['c', 'd']], dtype='<U4')