In [ ]:
import numpy as np

In [ ]:
ar = np.array([[1,2,3],[4,5,6]])
print(ar)

[[1 2 3]
 [4 5 6]]


In [ ]:
list = [1,2,3]
a = np.array(list,)
print("a:",a)
print(a.dtype)
a.itemsize

a: [1 2 3]
int64


8

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
list = [1,2,3]
a = np.array(list,dtype=float)
print("a:",a)
print(a.dtype)
a.itemsize

a: [1. 2. 3.]
float64


8

In [ ]:
list = ['abc','raj1']
a = np.array(list)
print("a:",a)
print(a.dtype)
print(a.itemsize)

a: ['abc' 'raj1']
<U4
16


In [ ]:
list = ['h','e','l','l','o']
a = np.array(list)
print("a:",a)
print(a.dtype)
print(a.itemsize)

a: ['h' 'e' 'l' 'l' 'o']
<U1
4


In [ ]:
list = [1,2,5,7,8,10,15,18]
a = np.array(list)
print("a:",a)
a[3]
a[-1]
a[-3]

a: [ 1  2  5  7  8 10 15 18]


10

In [ ]:
 ab = np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]])
print(ab)
print("Index Values : ",ab[2][5])
print('First Array: ',ab[0])
ab[-2][1]

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
Index Values :  6
First Array:  [1 2 3 4 5 6 7 8]


2

In [ ]:
list = [1,2,5,7,8,10,15,18]
a = np.array(list)
print(a)
print(a[-5:-3])
print(a[-5:])
a[2:6:2]

[ 1  2  5  7  8 10 15 18]
[7 8]
[ 7  8 10 15 18]


array([5, 8])

In [ ]:
for i in range(2,51,2):
    print(i)

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50


In [ ]:
a = np.arange(0,100)
print("\nArray is :- \n",a)
print("\nOdd Number is :- \n",a[1:100:2])
a[0:101:2].size


Array is :- 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

Odd Number is :- 
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


50

In [ ]:
a = np.arange(0,135)
print(a)
a[7:106:7]

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134]


array([  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84,  91,
        98, 105])